### ISSUE TITLE
Pick element

### ISSUE THREAD

**Issue by nenmilic** [wtlin1228/web-presenter#1]
Trying to pick element from menu (in front) but higlight window is in background:

![Screenshot_4](https://github.com/user-attachments/assets/a22c5e31-fa29-4cc2-a1a7-61a019d86b72)

**Comment by nenmilic** [comment]
Site: https://sampedro.dk/
1. Open menu, pick element on menu
![image](https://github.com/user-attachments/assets/b0d70819-c718-412e-8cfd-a14cd663d683)
2. Higlight is under menu:
![image](https://github.com/user-attachments/assets/d4b407d0-6d78-42fe-b8e8-6b12af8ad249)
3. When menu is hiden:
![image](https://github.com/user-attachments/assets/45ccfaa0-5b82-408b-b464-1c4d217e5c72)

**Comment by wtlin1228** [comment]
Thanks for reporting this issue, I think the cause is the side's z-index is below the menu's z-index of this website. I am planning to fix it by setting the z-index to maximum value.

**Comment by wtlin1228** [comment]
@nenmilic I had submitted the fixed version to chrome web store for review. The new version (1.0.0) will be published automatically after it passes the review stage. 

Thanks for reporting this issue again. 🫡
